#!/usr/bin/env python3
"""Pass 4: Final boost for all remaining tutorials below 500 prose words."""
import re, os

BOOST = {
"16s-rrna-prokka-annotation": [
    "The 16S ribosomal RNA gene serves as a universal phylogenetic marker for bacterial identification because it is present in all prokaryotes, contains both highly conserved regions suitable for primer design and hypervariable regions that provide taxonomic resolution. Amplicon sequencing of the 16S rRNA gene has been the standard approach for characterizing microbial community composition for over two decades, and the associated databases and analysis pipelines represent some of the most mature resources in microbial ecology. Understanding the principles and limitations of 16S-based profiling is essential for interpreting microbiome studies and for designing experiments that maximize taxonomic resolution while controlling for known biases in primer specificity, amplicon length, and sequencing platform.",
    "PROKKA provides rapid and accurate functional annotation of prokaryotic genomes by coordinating multiple prediction tools into a single automated pipeline. It identifies coding sequences, ribosomal RNA genes, transfer RNA genes, and signal peptides, then assigns functional annotations by searching against curated databases in a hierarchical manner that prioritizes high-confidence matches. For researchers working with newly assembled bacterial genomes or metagenomic bins, PROKKA transforms raw nucleotide sequences into biologically annotated gene catalogs that can be used for comparative genomics, metabolic reconstruction, and antimicrobial resistance gene identification. The annotation quality depends on the completeness of the input assembly and the representation of closely related organisms in the reference databases.",
],
"advanced-ai-single-cell": [
    "Artificial intelligence and machine learning approaches are increasingly being applied to single-cell genomics to address challenges that traditional statistical methods handle with difficulty. Automated cell type annotation, which historically required manual inspection of marker gene expression across clusters, can now be performed using trained classifiers that leverage reference atlases containing millions of annotated cells. Tools such as CellTypist employ logistic regression models trained on curated cell type references, while newer approaches based on large language models and foundation models can integrate textual descriptions of cell types with expression patterns to provide more nuanced and context-aware annotations.",
    "The distinction between supervised and unsupervised AI approaches in single-cell analysis reflects different analytical goals. Supervised methods such as CellTypist and scANVI require labeled reference datasets and excel at transferring known annotations to new datasets from similar tissues and conditions. Unsupervised approaches, including variational autoencoders and self-supervised foundation models, learn representations of cellular state without requiring pre-existing labels and can discover novel cell types or transitional states that are not represented in reference atlases. Understanding when each approach is appropriate and how to evaluate their predictions is critical for avoiding over-reliance on automated annotations that may not accurately reflect the biology of a specific experimental system.",
],
"advanced-visualization-packages": [
    "Publication-quality visualization is not merely an aesthetic concern but a fundamental component of scientific communication that directly affects how readers interpret and evaluate research findings. Default plots from Seurat or Scanpy, while adequate for exploratory analysis, rarely meet the standards expected by peer-reviewed journals in terms of resolution, color accessibility, labeling, and visual clarity. Specialized visualization packages such as SCpubr, dittoSeq, and scCustomize were developed specifically to bridge this gap, providing high-level functions that generate presentation-ready figures with consistent styling, colorblind-friendly palettes, and professional typography without requiring extensive manual customization.",
    "The choice of visualization package should be guided by the specific requirements of each figure and the target audience. SCpubr excels at creating complex multi-panel figures with harmonized aesthetics, while dittoSeq provides particularly strong support for color accessibility and is well-suited for publications that must comply with inclusive design guidelines. SCP and scplotter offer unique capabilities for three-dimensional embeddings and animated visualizations that can be valuable for presentations and supplementary materials. Combining multiple packages within a single project, using each for its particular strengths, represents a practical strategy for producing a cohesive and professionally presented set of figures.",
],
"cell-cell-communication": [
    "Cell-cell communication is the biological mechanism through which cells coordinate their behavior within tissues, orchestrating processes from immune activation to tissue repair and tumor progression. Computational inference of these signaling networks from single-cell transcriptomic data has emerged as a major application of scRNA-seq, providing insights that complement experimental methods such as co-culture assays and receptor blocking experiments. The fundamental approach involves matching the expression of known ligand genes in sender cell populations with the expression of their cognate receptor genes in receiver populations, then applying statistical frameworks to assess whether observed co-expression patterns exceed what would be expected by chance.",
    "Tools such as CellChat, LIANA, and NicheNet differ in their underlying databases of ligand-receptor interactions, statistical models for scoring communication probability, and methods for aggregating pairwise interactions into pathway-level or cell-type-level summaries. CellChat uses mass action-based kinetics to model signaling probability and provides rich visualization capabilities including chord diagrams, bubble plots, and river plots. LIANA takes a consensus approach by integrating results across multiple inference methods and interaction databases, providing more robust predictions at the cost of additional computational overhead. Choosing among these tools requires understanding their methodological assumptions and validating key predictions against independent experimental evidence.",
],
"cite-seq-wnn-multiomics": [
    "CITE-seq (Cellular Indexing of Transcriptomes and Epitopes by Sequencing) represents a significant advance in multi-modal single-cell profiling by simultaneously measuring gene expression and surface protein abundance in the same individual cells. This dual measurement is particularly valuable for immunological studies where surface protein markers define functional cell states that may not be fully captured by transcriptomic data alone. For example, distinguishing between naive and memory T cell subsets, or between classical and non-classical monocytes, often requires protein-level information from markers such as CD45RA, CD45RO, CD14, and CD16 that complement but do not duplicate the information provided by mRNA expression.",
    "Weighted Nearest Neighbor (WNN) analysis, implemented in Seurat v4 and later, provides a principled framework for integrating RNA and protein modalities by learning cell-specific weights that reflect the relative informativeness of each modality for each cell. In cell populations where surface protein expression provides clear discriminative power, WNN automatically upweights the protein modality, while in populations where transcriptomic differences are more informative, the RNA modality receives greater weight. This adaptive weighting produces integrated embeddings and clusters that leverage the complementary strengths of both data types, resulting in more biologically accurate cell type definitions than either modality alone could achieve.",
],
"command-line-part1": [
    "The Unix command line is the foundational interface through which virtually all bioinformatics analysis is conducted. While graphical tools exist for many common tasks, the command line provides unmatched flexibility, reproducibility, and scalability that are essential for processing the large datasets typical of modern genomics. Learning to navigate the file system, manage directories, and manipulate files from the terminal is not merely a technical skill but a prerequisite for every subsequent bioinformatics workflow.",
    "Understanding the hierarchical file system structure of Unix-like operating systems is the first conceptual hurdle for biologists transitioning to computational work. An absolute path begins from the root directory and uniquely identifies any file on the system, while a relative path describes a location in relation to your current working directory. The distinction between these two path types is critical for writing reproducible scripts, because absolute paths ensure your commands work regardless of where they are executed, while relative paths make your code portable across different systems where the directory structure may vary.",
],
"command-line-part3": [
    "Advanced shell scripting transforms the command line from a tool for individual tasks into a platform for building complete, automated analysis pipelines. While basic commands handle simple operations, real bioinformatics workflows require conditional logic, loop constructs, variable substitution, and error handling. AWK is a complete programming language designed specifically for processing structured text data, making it exceptionally well-suited for biological file formats where each line contains multiple tab-separated fields with different data types.",
    "Pipes and redirects are the connective tissue that links individual commands into coherent workflows. The pipe operator sends the output of one command directly as input to the next, creating processing chains that can filter, transform, and summarize data in a single compound command. Understanding these input and output mechanisms is essential for constructing the multi-step data processing pipelines that form the backbone of modern computational biology.",
],
"docker-singularity-bioinformatics": [
    "Containerization addresses one of the most persistent challenges in computational biology: ensuring that software environments can be precisely reproduced across different computing systems. Traditional software installation on shared HPC systems often leads to version conflicts, missing dependencies, and incompatible library versions that make it extremely difficult to reproduce analyses performed on different machines or at different points in time. Docker containers encapsulate an application along with all its dependencies, libraries, and configuration into a single portable unit that runs identically regardless of the host system.",
    "Singularity (now Apptainer) was developed specifically to address the security constraints of shared HPC environments where Docker's requirement for root privileges makes it unsuitable. Singularity containers can be built from Docker images, providing access to the vast ecosystem of pre-built bioinformatics containers on Docker Hub and BioContainers, while operating within the unprivileged user context required by multi-user computing clusters. Understanding how to pull, build, and run containers on both local workstations and remote HPC systems enables researchers to create fully reproducible computational environments that can be archived alongside publications and shared with collaborators.",
],
"infercnv-copy-number-variation": [
    "Copy number variation (CNV) detection from single-cell RNA-seq data provides a powerful method for distinguishing malignant cells from normal cells within the tumor microenvironment without requiring separate DNA sequencing. The inferCNV algorithm detects large-scale chromosomal gains and deletions by analyzing systematic deviations in gene expression levels across contiguous genomic regions, comparing expression patterns in putative tumor cells against a reference population of normal cells from the same dataset.",
    "The biological rationale underlying inferCNV is that chromosomal amplifications increase the dosage of all genes within the affected region, leading to coordinate upregulation of expression across contiguous genomic segments, while deletions cause coordinate downregulation. By averaging expression across sliding windows of genes ordered by chromosomal position, inferCNV transforms noisy single-gene expression measurements into smoothed chromosomal-scale signals that reveal the landscape of copy number alterations characteristic of different cancer subtypes. This information is invaluable for studying tumor heterogeneity, tracking clonal evolution, and identifying the specific genomic alterations that drive malignant phenotypes.",
],
"long-read-pacbio-nanopore": [
    "Long-read sequencing technologies from Oxford Nanopore and Pacific Biosciences have fundamentally expanded the scope of genomics by generating reads that span thousands to hundreds of thousands of base pairs. This length advantage enables direct resolution of repetitive sequences, structural variants, and full-length transcript isoforms that are invisible or ambiguous in short-read data. For genome assembly, long reads can span repetitive elements that fragment short-read assemblies, yielding contiguous chromosome-scale scaffolds. For transcriptomics, full-length cDNA reads eliminate the need for computational transcript reconstruction, providing unambiguous identification of alternative splicing events, gene fusions, and novel transcript isoforms.",
    "The analytical workflows for long-read data differ substantially from established short-read pipelines due to the distinct error profiles and read length distributions of each platform. Oxford Nanopore reads historically exhibited higher per-base error rates concentrated in homopolymer regions, though recent chemistry improvements have substantially reduced this limitation. PacBio HiFi reads achieve accuracy comparable to short reads through circular consensus sequencing, making them particularly suitable for variant calling applications. Understanding the strengths and limitations of each platform is essential for selecting appropriate tools and interpreting results correctly.",
],
"metagenomics-assembly-mapping": [
    "Metagenomic assembly reconstructs contiguous genome sequences from the fragmented short reads generated by shotgun sequencing of environmental or clinical samples. Unlike single-organism assembly, which benefits from relatively uniform coverage depth across the genome, metagenomic assembly must contend with highly uneven coverage distributions reflecting the wide range of species abundances in natural microbial communities. Abundant species may have thousands-fold coverage while rare species may have only a handful of reads, creating a computational challenge that requires specialized assembly algorithms designed to handle this complexity.",
    "Read mapping against assembled contigs or reference genomes serves multiple analytical purposes in metagenomics. Coverage depth across contigs provides quantitative estimates of species abundance, while the pattern of mapped reads reveals structural features such as genomic islands, mobile genetic elements, and regions of active horizontal gene transfer. Visualization of read alignments in tools such as IGV enables manual inspection of assembly quality and can reveal chimeric contigs, misassemblies, or contaminating sequences that automated quality metrics may not detect.",
],
"metagenomics-kraken2-bracken": [
    "Taxonomic classification of metagenomic reads is the foundational analysis step that answers the question of which organisms are present in a sample and at what relative abundances. Kraken2 uses an exact k-mer matching algorithm that compares short subsequences of each read against a database of reference genomes, assigning each read to the lowest common ancestor of all species sharing matching k-mers. This approach achieves classification speeds of millions of reads per minute, making it practical for processing the large sequencing datasets generated by modern shotgun metagenomics experiments.",
    "Bracken (Bayesian Reestimation of Abundance with KrakEN) addresses a fundamental limitation of Kraken2 by redistributing reads assigned to internal taxonomic nodes down to the species level using a Bayesian framework informed by expected read distributions from each reference genome. Without this correction, a substantial fraction of reads may be assigned only to genus or family level due to sequence conservation, leading to underestimation of species-level diversity. The combination of Kraken2 for initial classification and Bracken for abundance reestimation has become a standard workflow in metagenomic profiling studies.",
],
"metatranscriptomics-functional-pathways": [
    "Functional pathway analysis of metatranscriptomic data reveals which metabolic processes are actively being performed by microbial communities, providing a layer of biological interpretation that goes beyond taxonomic composition alone. While metagenomics tells us which organisms are present and what functional potential they encode, metatranscriptomics captures the actual gene expression activity at the time of sampling, distinguishing between dormant and metabolically active community members. This distinction is particularly important in dynamic environments such as the human gut, soil ecosystems, and wastewater treatment systems where community activity can change rapidly in response to environmental perturbations.",
    "HUMAnN 3 provides an integrated framework for mapping metatranscriptomic reads to metabolic pathways defined in the MetaCyc database, producing quantitative profiles of pathway abundance and coverage. The algorithm employs a tiered search strategy that first maps reads against known pangenomes for rapid classification, then performs translated search against the UniRef protein database for reads that cannot be assigned by nucleotide-level mapping. This approach balances computational efficiency with sensitivity for detecting novel functional activities not represented in existing reference genomes.",
],
"metatranscriptomics-guide": [
    "Metatranscriptomics extends the metagenomics paradigm by sequencing RNA rather than DNA, thereby capturing the actively transcribed genes within a microbial community at the time of sampling. This functional snapshot is essential for understanding community dynamics because the presence of a gene in a metagenome does not guarantee its expression, and many metabolic capabilities may be encoded but dormant under specific environmental conditions. By comparing metatranscriptomic and metagenomic profiles from the same samples, researchers can calculate relative expression ratios that distinguish constitutively active pathways from those induced only under specific conditions.",
    "The analytical workflow for metatranscriptomic data includes several preprocessing steps that are not required for metagenomic analysis. Ribosomal RNA removal is critical because rRNA can constitute 80 to 95 percent of total RNA, and its retention in the analysis dilutes the signal from messenger RNA transcripts that encode functional information. Computational rRNA filtering using tools such as SortMeRNA or ribodetector must be applied after sequencing, complementing the wet-lab depletion methods that are standard in library preparation protocols. Additionally, the rapid degradation kinetics of mRNA compared to DNA necessitate strict attention to sample handling and preservation protocols to ensure that measured expression profiles accurately reflect in vivo conditions.",
],
"phylogenomics-orthofinder": [
    "Phylogenomics extends traditional phylogenetic analysis from single genes to entire genomes, providing substantially greater statistical power for resolving evolutionary relationships between species. OrthoFinder automates the challenging process of identifying orthologous gene groups across multiple species, constructing gene trees for each orthogroup, reconciling gene trees with species trees to account for gene duplication and loss events, and inferring a final species phylogeny supported by thousands of individual gene histories.",
    "The identification of orthologs, genes in different species that descended from a common ancestral gene through speciation events, is fundamental to comparative genomics because orthologs are expected to retain similar functions across species. OrthoFinder distinguishes orthologs from paralogs, which arise through gene duplication, using a graph-based clustering algorithm that groups genes by sequence similarity and then infers the evolutionary relationships within each cluster. This distinction is essential for functional annotation transfer, comparative expression analysis, and accurate phylogenetic reconstruction.",
],
"reproducible-workflows-snakemake-nextflow": [
    "Workflow management systems such as Snakemake and Nextflow address the reproducibility crisis in bioinformatics by providing formal frameworks for defining, executing, and sharing computational pipelines. Ad hoc collections of shell scripts, while common in practice, are inherently fragile because they lack mechanisms for dependency tracking, parallel execution management, error recovery, and provenance recording. When an analysis involves dozens of interdependent steps operating on hundreds of input files, manually managing execution order, detecting which steps need to be rerun after parameter changes, and ensuring consistent software environments becomes prohibitively complex and error-prone.",
    "Snakemake and Nextflow represent two different design philosophies for workflow definition. Snakemake uses a Python-based domain-specific language that defines workflows in terms of output files and the rules that generate them, automatically inferring execution order through dependency resolution. Nextflow uses a dataflow programming model where processes communicate through channels, providing natural support for streaming data between pipeline steps. Both systems integrate with container technologies for environment management, support execution on local machines, HPC clusters, and cloud platforms, and provide monitoring interfaces for tracking pipeline progress. Choosing between them depends on personal preference, existing infrastructure, and the specific requirements of your workflows.",
],
"scrna-seq-integration-strategies": [
    "Batch effects represent one of the most pervasive challenges in single-cell genomics. Whenever samples are processed on different days, sequenced on different lanes, or prepared using different reagent lots, systematic technical variation is introduced that can confound biological signal. Without proper correction, these batch effects can cause cells to cluster by sample origin rather than by cell type, leading to false biological conclusions.",
    "Harmony, RPCA, and CCA represent three fundamentally different mathematical philosophies for solving the integration problem. Harmony operates in PCA space and iteratively adjusts cell embeddings using soft k-means clustering and ridge regression, making it fast and memory-efficient for large datasets. Reciprocal PCA identifies shared biological variation by projecting each dataset into the other's PCA space and finding mutual nearest neighbors, which is more conservative and less likely to over-correct genuine biological differences. CCA identifies correlated gene programs across datasets by maximizing the correlation between shared canonical variates, making it powerful when datasets share cell types but have substantial technical differences.",
],
"scrna-seq-quality-control": [
    "Mathematical quality control provides objective, quantitative evidence that batch integration has succeeded and that identified clusters represent genuine biological entities rather than artifacts of the analytical pipeline. While UMAP visualizations are commonly used to assess integration quality, they are inherently unreliable for this purpose because the same high-dimensional data can produce visually different embeddings depending on random initialization and parameter settings. Quantitative metrics such as LISI (Local Inverse Simpson's Index) and Silhouette scores provide reproducible numerical assessments that can be compared across methods, parameters, and datasets.",
    "The LISI framework evaluates integration quality by measuring the local diversity of batch labels around each cell in the integrated embedding. Well-integrated data should show high batch mixing, meaning that each cell's local neighborhood contains cells from multiple batches in proportion to their overall representation. Simultaneously, cells should cluster by cell type rather than by batch, meaning that the biological labels should show low local diversity within clusters. The Silhouette score complements LISI by measuring how similar each cell is to other cells in its assigned cluster compared to cells in the nearest neighboring cluster, providing a direct assessment of cluster compactness and separation.",
],
"scrna-seq-trajectory-inference": [
    "Trajectory inference reconstructs the continuous progression of cellular states from discrete single-cell snapshots, enabling researchers to study dynamic biological processes such as differentiation, activation, and disease progression from data collected at a single time point. The fundamental insight underlying trajectory analysis is that a population of cells captured simultaneously will include cells at different stages of a continuous process, and by ordering these cells computationally along a pseudotime axis, the temporal dynamics of gene expression can be reconstructed without requiring time-series sampling.",
    "Different trajectory inference methods make different assumptions about the topology of the underlying biological process. PAGA (Partition-based Graph Abstraction) in Scanpy provides a coarse-grained trajectory structure by connecting clusters based on the density of inter-cluster edges in the neighborhood graph, enabling discovery of branching topologies without requiring prior knowledge. Monocle3 in R learns the trajectory graph using principal graph methods and assigns pseudotime values from user-specified root cells. Slingshot constructs lineage-specific pseudotime orderings using principal curves that pass through clusters in a user-defined order. Selecting the appropriate method requires considering the expected trajectory topology, whether branching is expected, and how much prior biological knowledge is available to guide the analysis.",
],
"single-cell-deconvolution": [
    "Bulk RNA-seq deconvolution uses single-cell reference data to computationally estimate the cellular composition of bulk tissue samples. This approach is valuable because bulk RNA-seq datasets are far more abundant, less expensive, and more readily available than single-cell data, particularly for clinical cohorts and archival samples. By leveraging the cell-type-specific gene expression signatures learned from scRNA-seq reference atlases, deconvolution methods can infer the proportions of different cell types present in each bulk sample, enabling large-scale association studies between cellular composition and clinical outcomes.",
    "Multiple computational frameworks exist for deconvolution, each with distinct statistical models and assumptions. MuSiC uses weighted non-negative least squares regression that accounts for cross-subject variability in cell-type-specific expression profiles. BisqueRNA provides both reference-based and marker-based deconvolution modes, offering flexibility when a perfectly matched single-cell reference is not available. CIBERSORTx uses support vector regression and provides additional functionality for imputing cell-type-specific gene expression profiles from bulk data. Evaluating deconvolution accuracy typically requires validation against independent measurements such as flow cytometry or immunohistochemistry, particularly when applying models trained on one tissue type or disease context to a different biological setting.",
],
"tcr-bcr-repertoire-analysis": [
    "Immune repertoire analysis examines the diversity and clonal dynamics of T-cell and B-cell receptor sequences, providing insights into adaptive immune responses that complement gene expression profiling. Each T cell and B cell carries a unique receptor sequence generated through somatic V(D)J recombination, and the distribution of these receptor sequences within a sample reflects the history of antigen exposure, clonal selection, and immune activation. In diseases such as Sezary Syndrome and other T-cell lymphomas, the immune repertoire is dominated by expanded malignant clones, and tracking these clonal populations provides direct evidence of disease burden and treatment response.",
    "Tools such as scRepertoire integrate receptor sequence data with single-cell transcriptomic profiles, enabling researchers to simultaneously characterize the phenotypic state and clonal identity of individual immune cells. This integration reveals how clonally expanded cells distribute across transcriptionally defined subpopulations, whether specific clonotypes are associated with particular functional states, and how clonal diversity changes between disease conditions or treatment time points. Metrics such as clonal diversity indices, clonotype sharing between samples, and preferential V-gene usage provide quantitative summaries of repertoire characteristics that can be compared statistically across experimental conditions.",
],
"transcriptomics-differential-expression": [
    "Differential gene expression analysis is the fundamental statistical framework for identifying genes whose expression levels change significantly between experimental conditions. In the context of bulk RNA-seq, tools such as DESeq2 and edgeR model count data using negative binomial distributions that account for both technical sampling noise and biological variability across replicates. The pseudobulk approach for single-cell data aggregates cell-level counts within each sample and cell type, creating sample-level count matrices that can be analyzed using the same well-validated bulk RNA-seq statistical frameworks while properly accounting for the hierarchical structure of single-cell experiments.",
    "The pseudobulk strategy is now considered the gold standard for differential expression testing in single-cell experiments because it correctly treats biological replicates rather than individual cells as the unit of statistical inference. Naive approaches that treat each cell as an independent observation dramatically inflate the degrees of freedom, leading to severely inflated false positive rates and p-values that are orders of magnitude too small. By aggregating counts at the sample level, pseudobulk analysis preserves the statistical rigor of established bulk RNA-seq methods while leveraging the cell-type resolution provided by single-cell clustering.",
],
"experimental-design-batch-effects": [
    "Biological replicates capture the natural variation between independent experimental units, such as individual patients, separate tissue samples, or independently cultured cell populations. This variation is essential for statistical inference because it defines the denominator of hypothesis tests and determines the generalizability of findings. Technical replicates, which measure the same biological sample multiple times, quantify measurement precision but do not contribute to estimating biological variability. Understanding this distinction is critical for correctly powering experiments.",
    "Batch effect mitigation strategies should be implemented at the experimental design stage rather than relying solely on computational correction methods. Balanced designs that distribute biological conditions evenly across processing batches ensure that batch effects and biological effects are orthogonal and therefore separable. When perfect balance is not achievable due to practical constraints, recording detailed metadata about sample processing enables post-hoc correction using methods such as ComBat or limma. The key principle is that batch effects can only be corrected if they are identifiable, which requires meticulous documentation of all processing variables.",
],
}

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    enhanced = 0
    for slug, paragraphs in BOOST.items():
        fpath = os.path.join(base, slug + ".html")
        if not os.path.exists(fpath):
            continue
        with open(fpath) as f:
            html = f.read()
        if paragraphs[0][:80] in html:
            print(f"  skip {slug}")
            continue
        # Insert before Knowledge Check
        for marker in ['<h2>Knowledge Check', '<h2>Next Steps', '<div class="mt-10 p-8']:
            idx = html.find(marker)
            if idx > 0:
                block = "\n".join(f"<p>{p}</p>" for p in paragraphs)
                html = html[:idx] + block + "\n" + html[idx:]
                with open(fpath, 'w') as f:
                    f.write(html)
                prose = ' '.join(re.findall(r'<p>(.*?)</p>', html, re.DOTALL))
                prose = re.sub(r'<[^>]+>', ' ', prose)
                pw = len(prose.split())
                print(f"  ✅ {slug}: {pw} words")
                enhanced += 1
                break
    print(f"\nPass 4: {enhanced} enhanced")

if __name__ == "__main__":
    main()
