#!/usr/bin/env python3
"""Pass 2: Inject per-h2 contextual prose paragraphs to bring every tutorial above 800 words."""
import re, os, json

# For each tutorial, map h2 substring -> extra paragraph(s) to inject after it.
# Written in proper academic style without em dashes.
DATA = {
"command-line-part2": {
  "Text Processing": "Text processing constitutes one of the most practically valuable competencies in the bioinformatics command-line toolkit. Biological data files, including FASTA sequences, VCF variant calls, GTF gene annotations, and SAM alignment records, are structured text formats that can be efficiently queried, filtered, and transformed using standard Unix utilities. Rather than loading a multi-gigabyte file into a spreadsheet application or writing custom scripts for simple operations, experienced bioinformaticians routinely use grep, sed, cut, and sort to accomplish in seconds what might otherwise require minutes of manual effort.",
  "grep": "The grep command (Global Regular Expression Print) searches input for lines matching a specified pattern and prints them to standard output. In bioinformatics, grep is indispensable for tasks such as extracting all entries for a specific chromosome from a BED file, counting the number of reads mapping to a particular gene, or searching log files for error messages during pipeline debugging. Regular expressions extend grep beyond simple string matching by allowing pattern specifications with wildcards, character classes, and quantifiers. This enables sophisticated queries such as finding all gene symbols beginning with HOX followed by any combination of letters and digits. Understanding the difference between basic and extended regular expression syntax is important, as it affects which metacharacters require escaping.",
  "sed": "The stream editor sed performs text transformations on input streams without requiring an interactive editor session. Its most common application in bioinformatics involves search-and-replace operations across large files, such as converting chromosome naming conventions between UCSC and Ensembl formats, standardizing sample identifiers in metadata files, or removing header lines from data files before piping them into downstream analysis tools. The substitution command follows the pattern s/old/new/flags, where flags control whether replacement occurs globally on each line or only for the first match. Mastering sed syntax enables batch transformations that would be tedious and error-prone if performed manually across thousands of lines.",
  "cut": "The cut command extracts specific columns from tabular data, which is essential for working with the column-delimited file formats that dominate bioinformatics. When extracting gene names from a GTF annotation file, isolating specific INFO fields from a VCF variant file, or selecting sample columns from an expression matrix, cut provides a fast and memory-efficient solution that does not require loading the entire file into memory. When combined with sort for ordering and uniq for deduplication, these tools enable rapid frequency counting, duplicate identification, and basic data summarization entirely from the command line without invoking a programming language interpreter.",
  "Conclusion": "Proficiency with text processing commands fundamentally changes how efficiently a bioinformatician can work with data. These tools are particularly valuable when working on high-performance computing clusters where graphical interfaces are unavailable, when debugging pipeline failures by inspecting intermediate output files, or when performing rapid sanity checks on large datasets before committing to computationally expensive downstream analyses. The composability of Unix commands through pipes means that individually simple tools can be combined into powerful data processing workflows that rival the functionality of dedicated scripting solutions.",
},
"scrna-seq-downstream-analysis": {
  "Downstream": "After completing the initial clustering of single-cell RNA-seq data, the biological interpretation phase begins with downstream analyses that extract functional insights from the identified cell populations. These analyses move beyond simply grouping cells by transcriptional similarity and instead aim to characterize the biological roles, signaling interactions, and regulatory programs that define each cell state. The three foundational downstream analyses covered in this tutorial, namely cell-cell communication, transcription factor activity inference, and publication-quality visualization, represent essential competencies for any researcher working with single-cell data in the context of immunology, oncology, or developmental biology.",
  "Communication": "Cell-cell communication analysis reconstructs the intercellular signaling networks that coordinate tissue function. By leveraging curated databases of known ligand-receptor interactions and combining them with cell-type-specific expression data, tools such as CellChat and LIANA infer which cell populations are likely communicating and through which molecular pathways. This information is critical for understanding how the tumor microenvironment sustains malignant growth, how immune cells coordinate responses to infection, or how stem cell niches maintain tissue homeostasis. The statistical frameworks underlying these tools account for the stochastic nature of single-cell expression data and provide confidence measures for each predicted interaction.",
  "Transcription Factor": "Transcription factor activity inference using tools such as decoupleR and DoRothEA moves beyond simply measuring gene expression levels to estimate the functional activity of regulatory proteins. This distinction is important because transcription factor activity depends on post-translational modifications, protein-protein interactions, and chromatin accessibility, none of which are directly captured by mRNA abundance measurements. By examining the coordinated expression of known target genes for each transcription factor, these methods provide a more biologically meaningful readout of regulatory state than expression of the transcription factor gene alone.",
  "Conclusion": "Together, these downstream analyses transform a clustered UMAP plot from a descriptive visualization into a rich source of biological hypotheses. The combination of intercellular communication mapping, regulatory activity profiling, and professional visualization provides a comprehensive analytical framework that supports both discovery-driven research and hypothesis validation in single-cell genomics studies.",
},
"4-Support": {
  "Diagnosing": "Effective troubleshooting on high-performance computing systems requires a systematic approach that differs substantially from debugging code on a personal laptop. HPC environments introduce additional complexity through shared resource management, queue scheduling, module-based software management, and multi-node job distribution. When a job fails, the source of the error may lie in the submission script configuration, resource allocation parameters, software environment, input data formatting, or infrastructure issues entirely outside the user's control. Developing a structured diagnostic workflow saves considerable time and reduces frustration when working with computationally intensive bioinformatics pipelines.",
  "man pages": "Manual pages and help flags represent the primary self-service documentation resources available on Unix systems. The man command provides comprehensive documentation for system commands, file formats, and library functions, organized into numbered sections that distinguish between user commands, system calls, and configuration files. For bioinformatics tools installed via package managers or compiled from source, the --help or -h flag typically provides a concise summary of available options and usage patterns. Learning to navigate these documentation resources efficiently is essential because bioinformatics tools are frequently updated, and online tutorials may describe parameters or behaviors from outdated versions.",
  "error logs": "Interpreting error logs is a critical skill that improves with experience and systematic practice. Slurm job schedulers generate both standard output and standard error streams, which should always be directed to separate log files using the --output and --error directives in submission scripts. Common error categories include out-of-memory kills (indicated by OOM or SIGKILL messages), wall-time exceeded notifications, file-not-found errors from incorrect paths, and permission denied errors when accessing shared storage. Maintaining a personal reference of previously encountered errors and their solutions significantly accelerates the debugging process for recurring issues.",
  "Conclusion": "Knowing when and how to contact cluster support is an important professional skill. System administrators can resolve infrastructure problems, adjust resource quotas, and identify system-wide issues that affect multiple users. When submitting a support request, including the job ID, error log contents, submission script, and a description of the expected versus observed behavior enables the support team to diagnose problems efficiently. Well-formulated support requests demonstrate professionalism and typically receive faster, more thorough responses.",
},
"spatial-transcriptomics-r-python": {
  "Spatial": "Spatial transcriptomics represents a transformative advance in genomics that preserves the physical location of gene expression measurements within intact tissue sections. Unlike dissociated single-cell RNA-seq, which captures transcriptomes but destroys spatial context during tissue dissociation, spatial methods retain the architectural relationships between cells. This spatial information is essential for understanding how tissue organization influences cellular function, how gradients of signaling molecules shape developmental patterning, and how the physical proximity of cell types within the tumor microenvironment affects immune infiltration and therapeutic response.",
  "tissue": "The integration of gene expression data with tissue morphology creates opportunities for analyses that are impossible with either modality alone. Researchers can identify spatially variable genes whose expression patterns correspond to histological features, map cell type distributions across tissue compartments, and detect localized signaling gradients that coordinate multicellular processes. Computational tools in both R (Seurat) and Python (Squidpy, Scanpy) provide complementary frameworks for these analyses, with each ecosystem offering unique strengths in visualization, statistical testing, and integration with existing single-cell workflows.",
  "Conclusion": "Spatial transcriptomics is rapidly evolving, with new technologies continuously improving both spatial resolution and transcriptomic coverage. Current platforms range from spot-based methods that capture small groups of cells to subcellular-resolution approaches that localize individual mRNA molecules. Understanding the analytical principles covered in this tutorial provides a foundation that transfers across platforms and will remain relevant as the technology continues to mature.",
},
"reproducible-project-structure": {
  "Reproducible": "Reproducibility is a cornerstone of scientific integrity, yet computational analyses frequently fail to meet even basic reproducibility standards. Studies have shown that a substantial proportion of published bioinformatics analyses cannot be independently replicated due to incomplete documentation, missing software version information, and disorganized file structures. Establishing a standardized project structure from the outset of an analysis project addresses these challenges systematically by creating a clear, self-documenting framework that facilitates both internal reproducibility and external review.",
  "data": "A well-organized project directory separates raw input data, processing scripts, intermediate results, and final outputs into clearly labeled subdirectories. Raw data should be treated as immutable and stored separately from any processed derivatives, ensuring that the original inputs can always be traced and the analysis can be re-executed from scratch if needed. Scripts should be numbered or ordered to reflect the analytical workflow, with each script reading from and writing to predictable locations. This organizational discipline is particularly important for collaborative projects where multiple researchers need to navigate the same file structure.",
  "Conclusion": "Investing time in project organization at the beginning of an analysis yields substantial returns throughout the project lifecycle. Structured projects are easier to debug when results are unexpected, simpler to extend when reviewers request additional analyses, and more straightforward to archive for long-term preservation. For graduate students and postdoctoral researchers, maintaining well-organized project repositories also facilitates the knowledge transfer that occurs when leaving a laboratory, ensuring that years of analytical work remain accessible and usable by future team members.",
},
"python-fundamentals-bioinformatics": {
  "Python": "Python has emerged as one of the two dominant programming languages in bioinformatics, alongside R, owing to its readable syntax, extensive scientific computing ecosystem, and strong community support. For biologists beginning their computational journey, Python offers a gentle learning curve that does not sacrifice power or flexibility. The language's design philosophy emphasizes code readability and simplicity, which makes Python scripts more accessible to collaborators who may not be experienced programmers. In the bioinformatics context, Python serves as the foundation for major analysis frameworks including Scanpy for single-cell analysis, Biopython for sequence manipulation, and pandas for tabular data processing.",
  "variables": "Understanding fundamental data types and data structures is essential before attempting to write bioinformatics scripts. Variables in Python can hold different types of data including strings (useful for DNA sequences and gene names), integers (for read counts and chromosome positions), floating-point numbers (for expression values and p-values), and boolean values (for logical filtering operations). Collections such as lists, dictionaries, and sets provide organized ways to store and access multiple related values, which is critical when working with biological data that inherently involves collections of genes, samples, and measurements.",
  "Conclusion": "Mastering Python fundamentals opens the door to the vast ecosystem of bioinformatics libraries that handle everything from sequence alignment to machine learning-based cell type annotation. The skills covered in this tutorial, including variable manipulation, file input/output, function definition, and basic string processing, form the building blocks for increasingly sophisticated analyses. Proficiency with these foundations enables you to read, modify, and debug existing bioinformatics scripts, which is often more valuable in practice than writing code from scratch.",
},
"r-tidyverse-fundamentals": {
  "R and": "R is the statistical programming language of choice for a large proportion of the bioinformatics community, particularly for statistical analysis, data visualization, and genomics applications. The Bioconductor repository provides thousands of specialized packages for genomic data analysis, including Seurat for single-cell RNA-seq, DESeq2 for differential expression, and clusterProfiler for functional enrichment. Understanding R fundamentals is therefore not merely an academic exercise but a practical necessity for any computational biologist who needs to interact with the broader bioinformatics ecosystem.",
  "vectors": "R's fundamental data structures, including vectors, data frames, matrices, and factors, are designed with statistical analysis in mind. Vectors are the atomic data type in R, and understanding how vectorized operations work is essential for writing efficient and idiomatic R code. Data frames, and their modern tidyverse equivalent tibbles, provide the tabular data structure that maps naturally to biological experiment metadata, gene expression matrices, and variant annotation tables. Factors encode categorical variables with defined levels, which is important for correctly specifying experimental conditions, tissue types, and treatment groups in statistical models.",
  "Conclusion": "The tidyverse collection of packages, including dplyr for data manipulation, ggplot2 for visualization, and tidyr for data reshaping, provides a consistent and readable grammar for data analysis that has become the standard approach in modern R programming. Learning to compose analytical workflows using pipe operators creates self-documenting code that reads like a description of the analysis steps, which significantly improves reproducibility and collaboration. These skills transfer directly to the single-cell analysis tutorials that follow in this learning path.",
},
"reference-genomes-annotation": {
  "Reference": "The choice of reference genome and gene annotation is one of the most consequential decisions in any genomics workflow, yet it is frequently treated as an afterthought. Using an outdated genome build, an incompatible annotation version, or mismatched identifier systems can introduce systematic errors that propagate through every subsequent analysis step, from read alignment to differential expression to functional interpretation. Understanding the relationship between genome assemblies, gene annotation databases, and identifier systems is essential for producing reliable and interpretable results.",
  "genome builds": "Major genome assembly versions such as GRCh37 (hg19) and GRCh38 (hg38) for human differ in coordinate systems, chromosome naming conventions, and the inclusion of alternative haplotype sequences and patch scaffolds. Mixing coordinates from different assemblies without proper liftover conversion is a common source of errors that can cause genes to be assigned incorrect genomic positions or missed entirely. Gene annotation databases including Ensembl, GENCODE, and RefSeq use different gene models, transcript definitions, and identifier systems, which means that gene counts produced using one annotation are not directly comparable to those produced using another.",
  "Conclusion": "Documenting the exact genome build, annotation version, and identifier mapping used in an analysis is a non-negotiable requirement for reproducible research. This information should be recorded in the methods section of any publication and preserved alongside the analysis code and results. When integrating data from multiple sources or comparing results across studies, verifying annotation compatibility should be the first quality control step before any biological interpretation is attempted.",
},
"data-visualization-fundamentals": {
  "Data Visualization": "Data visualization serves dual purposes in bioinformatics: it is both an analytical tool for exploring data and discovering patterns, and a communication tool for presenting findings to collaborators and reviewers. Effective visualization requires understanding not just the technical mechanics of generating plots, but also the perceptual principles that determine how humans interpret visual information. Color choices, axis scaling, aspect ratios, and annotation placement all influence whether a figure accurately conveys the underlying data or inadvertently misleads the viewer.",
  "QC plots": "Quality control visualizations are among the most important plots in any bioinformatics workflow because they inform the filtering decisions that shape all downstream results. Distribution plots of key metrics such as library size, gene detection rate, and mitochondrial content reveal sample quality and help identify outlier cells or failed samples. PCA plots and their nonlinear counterparts (UMAP, t-SNE) provide low-dimensional summaries of high-dimensional data, but these embeddings involve information loss and parameter sensitivity that must be acknowledged when drawing biological conclusions.",
  "Conclusion": "The distinction between exploratory visualization and publication-ready figures is important for efficient workflow management. During analysis, quick diagnostic plots with default aesthetics are sufficient for decision-making. Final figures for manuscripts and presentations, however, require careful attention to color accessibility, font sizes appropriate for the target display medium, and consistent styling across all panels. Establishing a visualization style guide early in a project ensures visual coherence across all figures and reduces the time spent on formatting during the final stages of manuscript preparation.",
},
"research-reporting-interpretation": {
  "Research": "Scientific communication is the mechanism through which experimental findings enter the shared knowledge base of the research community. For computational analyses in particular, the methods section must contain sufficient detail to enable independent replication, including software versions, parameter settings, reference datasets, and any manual curation steps. The growing emphasis on reproducibility in genomics has raised the standard for methods reporting, and journals increasingly require that code, data, and computational environments be made publicly available alongside published manuscripts.",
  "methods": "Writing reproducible methods descriptions requires balancing completeness with readability. Every analytical choice that could affect the results should be documented, but the narrative should flow logically rather than reading as a parameter dump. Effective strategies include organizing the methods in the order of the analytical workflow, grouping related tools and parameters together, and providing brief justifications for non-standard choices. Figure legends should describe what is shown, how it was generated, and what statistical tests were applied, enabling readers to evaluate the evidence independently.",
  "Conclusion": "Biological interpretation is the most intellectually demanding aspect of computational research because it requires integrating quantitative results with domain-specific knowledge to generate meaningful conclusions. Over-interpreting statistical associations as causal relationships, drawing conclusions from underpowered analyses, or ignoring confounding variables are common pitfalls that undermine the credibility of otherwise technically sound work. Maintaining intellectual honesty about the limitations of the data and analysis methods is essential for producing research that withstands scrutiny and contributes meaningfully to scientific progress.",
},
"experimental-design-batch-effects": {
  "Experimental": "Experimental design is arguably the most critical determinant of whether a genomics study will yield reliable and interpretable results. No amount of computational sophistication can rescue a poorly designed experiment, because confounding between biological variables of interest and technical batch effects renders the data fundamentally uninterpretable. Planning the allocation of biological replicates across sequencing batches, recording potential covariates, and anticipating sources of technical variation before generating data is far more efficient than attempting to correct for design flaws after the fact.",
  "replicates": "Biological replicates capture the natural variation between independent experimental units, such as individual patients, separate tissue samples, or independently cultured cell populations. This variation is essential for statistical inference because it defines the denominator of hypothesis tests and determines the generalizability of findings. Technical replicates, which measure the same biological sample multiple times, quantify measurement precision but do not contribute to estimating biological variability. Understanding this distinction is critical for correctly powering experiments and for specifying appropriate statistical models that account for the hierarchical structure of biological data.",
  "Conclusion": "Batch effect mitigation strategies should be implemented at the experimental design stage rather than relying solely on computational correction methods. Balanced designs that distribute biological conditions evenly across processing batches ensure that batch effects and biological effects are orthogonal and therefore separable. When perfect balance is not achievable due to practical constraints, recording detailed metadata about sample processing enables post-hoc correction using methods such as ComBat or limma's removeBatchEffect. The key principle is that batch effects can only be corrected if they are identifiable, which requires meticulous documentation of all processing variables.",
},
"git-github-bioinformatics": {
  "Git": "Version control is a foundational practice for reproducible computational research that has been widely adopted from software engineering into bioinformatics. Git tracks every change made to every file in a project, creating a complete history that enables researchers to understand how an analysis evolved over time, revert to previous states when experiments fail, and identify exactly when a particular result was generated. For collaborative projects involving multiple analysts, Git provides mechanisms for concurrent development, conflict resolution, and attribution of individual contributions.",
  "GitHub": "GitHub extends Git's local version control capabilities with remote hosting, collaboration features, and project management tools that are increasingly important for scientific computing. Public repositories serve as supplementary materials for publications, providing reviewers and readers with access to the exact code used to generate published results. Issues and pull requests create documented records of analytical decisions and code review processes. GitHub Actions can automate quality checks, test pipelines, and documentation generation, ensuring that shared code maintains consistent quality standards.",
  "Conclusion": "Adopting version control early in a research career pays compounding dividends over time. The initial investment in learning Git commands and workflows is modest compared to the long-term benefits of having a complete, searchable record of every analytical decision, a reliable backup system for code and documentation, and a professional portfolio of computational work that demonstrates technical competence to future employers, collaborators, and grant reviewers.",
},
"statistics-for-bioinformatics": {
  "Statistics": "Statistical reasoning is the framework that enables bioinformaticians to distinguish genuine biological signals from technical noise and random variation. Genomics datasets are characterized by high dimensionality, complex correlation structures, and heterogeneous noise profiles that violate the assumptions of many classical statistical tests. Understanding which statistical methods are appropriate for different data types and experimental designs, and recognizing when assumptions are violated, is essential for producing analyses that withstand scientific scrutiny.",
  "distributions": "Probability distributions provide the mathematical models that describe the expected behavior of biological measurements under null hypotheses. Gene expression count data from RNA-seq experiments typically follow negative binomial distributions, which account for both the Poisson sampling noise inherent in sequencing and the biological overdispersion observed across samples. Continuous measurements such as protein abundance or metabolite concentrations may approximate normal or log-normal distributions. Choosing an appropriate distributional model for the data type being analyzed is a prerequisite for valid statistical inference, as misspecified models can lead to inflated false positive rates or reduced statistical power.",
  "Conclusion": "Multiple testing correction is perhaps the most important statistical concept for genomics researchers to internalize. When testing thousands of genes simultaneously for differential expression, the expected number of false positives under the null hypothesis scales linearly with the number of tests. Methods such as the Benjamini-Hochberg procedure control the false discovery rate by adjusting p-values to account for the multiplicity of comparisons. Failure to apply appropriate correction leads to results dominated by false positives, which wastes validation resources and erodes confidence in computational findings.",
},
"biological-data-formats": {
  "Biological Data": "Understanding the standard file formats used in bioinformatics is a prerequisite for every computational analysis, from quality control through to biological interpretation. Each format was designed to encode specific types of biological information efficiently, and the conventions governing field ordering, coordinate systems, and header specifications are not arbitrary but reflect practical requirements for interoperability between tools. Misinterpreting coordinate conventions, confusing zero-based and one-based indexing, or mishandling header metadata are among the most common sources of errors in bioinformatics pipelines.",
  "FASTA": "The FASTA and FASTQ formats represent nucleotide and protein sequences, with FASTQ additionally encoding per-base quality scores that reflect the confidence of each base call. Understanding Phred quality scores and their relationship to base call error probabilities is essential for setting appropriate quality filtering thresholds during read preprocessing. SAM/BAM formats encode read alignments against a reference genome and contain rich metadata including mapping quality, CIGAR strings describing the alignment structure, and optional tags recording information such as mate pair status and duplicate marking flags.",
  "Conclusion": "Familiarity with these formats enables you to inspect intermediate files at any stage of a pipeline, which is invaluable for debugging unexpected results. Tools such as samtools, bcftools, bedtools, and tabix provide efficient random access and manipulation capabilities for these formats. Developing the habit of examining file contents directly rather than relying solely on downstream tool output builds the diagnostic intuition that distinguishes proficient bioinformaticians from those who treat their workflows as opaque black boxes.",
},
"quality-control-fundamentals": {
  "Quality Control": "Quality control is the analytical gatekeeper that determines whether downstream results reflect genuine biology or are dominated by technical artifacts. In genomics experiments, sources of technical variation include library preparation efficiency, sequencing depth, sample degradation, reagent lot effects, and instrument performance fluctuations. QC procedures must be applied at every stage of the analytical workflow, from raw read assessment through alignment evaluation to final data interpretation, because different types of artifacts manifest at different stages and require distinct detection strategies.",
  "read quality": "Read-level quality assessment using tools such as FastQC and MultiQC examines the distribution of base quality scores, GC content, adapter contamination, sequence duplication levels, and overrepresented sequences across all reads in a sequencing run. These metrics collectively characterize the technical quality of the sequencing data and can reveal problems such as failed flow cell tiles, contamination from adapter dimers, or library complexity issues that affect the interpretability of downstream analyses. Importantly, QC metrics should be evaluated in the context of the specific experiment type, as expected metric distributions differ substantially between whole-genome sequencing, targeted capture, and single-cell protocols.",
  "Conclusion": "The philosophy underlying quality control in bioinformatics is fundamentally about establishing confidence in the data before investing computational resources in analysis and biological interpretation. Spending time on thorough QC at the beginning of a project prevents the far more costly scenario of discovering data quality issues after weeks of analysis, which may necessitate repeating the entire computational workflow or, in severe cases, regenerating the experimental data. Systematic QC documentation also strengthens the methods section of publications by demonstrating rigorous attention to data quality.",
},
}

def inject_prose(filepath, slug_data):
    with open(filepath) as f:
        html = f.read()
    changed = False
    for heading_sub, para_text in slug_data.items():
        if para_text in html:
            continue
        p_tag = f"<p>{para_text}</p>"
        # Find h2 containing the substring
        pat = re.compile(r'(<h2>[^<]*' + re.escape(heading_sub) + r'[^<]*</h2>\s*<p>.*?</p>)', re.DOTALL)
        m = pat.search(html)
        if m:
            html = html[:m.end()] + "\n" + p_tag + html[m.end():]
            changed = True
        else:
            # Try inserting before Conclusion or Knowledge Check
            for marker in ['<h2>Conclusion</h2>', '<div class="mt-10 p-8 bg-gray-50']:
                idx = html.find(marker)
                if idx > 0:
                    html = html[:idx] + p_tag + "\n" + html[idx:]
                    changed = True
                    break
    if changed:
        with open(filepath, 'w') as f:
            f.write(html)
    return changed

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    enhanced = 0
    for slug, prose_map in DATA.items():
        fpath = os.path.join(base, slug + ".html")
        if not os.path.exists(fpath):
            print(f"  ⚠️  {slug}.html not found, skipping")
            continue
        if inject_prose(fpath, prose_map):
            # Recount
            with open(fpath) as f:
                html = f.read()
            prose = ' '.join(re.findall(r'<p>(.*?)</p>', html, re.DOTALL))
            prose = re.sub(r'<[^>]+>', ' ', prose)
            pw = len(prose.split())
            print(f"  ✅ {slug}.html: now {pw} prose words")
            enhanced += 1
        else:
            print(f"  ⏭️  {slug}.html: no changes")
    print(f"\nPass 2 enhanced: {enhanced} tutorials")

if __name__ == "__main__":
    main()
